version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  warehouse-service-1:
    build:
      context: .
      dockerfile: warehouse-service/Dockerfile
    ports:
      - "3344:3344/udp"
      - "3355:3355/udp"
    environment:
      WAREHOUSE_ID: "warehouse-1"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      NO_SENSOR_DATA_TIMEOUT: 60000
    depends_on:
      - kafka

  central-monitoring-service:
    build:
      context: .
      dockerfile: central-monitoring-service/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      KAFKA_GROUP_ID_SENSORS: "central-monitoring-sensors"
      KAFKA_GROUP_ID_WARNINGS: "central-monitoring-warnings"
      KAFKA_AUTO_OFFSET_RESET: "earliest"
    depends_on:
      - kafka

  warehouse-service-2:
    build:
      context: .
      dockerfile: warehouse-service/Dockerfile
    ports:
      - "3366:3366/udp"
      - "3377:3377/udp"
    environment:
      WAREHOUSE_ID: "warehouse-2"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      NO_SENSOR_DATA_TIMEOUT: 60000
    depends_on:
      - kafka